---
- name: restart containerd
  ansible.builtin.service: 
    name: containerd
    state: restarted
    enabled: yes

- name: restart docker
  ansible.builtin.service: 
    name: docker
    state: restarted
    enabled: yes