---
- name: restart containerd
  ansible.builtin.service: 
    name: containerd
    state: started
    enabled: yes

- name: start docker
  ansible.builtin.service: 
    name: docker.service
    state: started
    enabled: yes
  become: true

- name: restart docker
  ansible.builtin.service: 
    name: docker.service
    state: restarted
    enabled: yes