---
- name: install web server
  yum:
    name: httpd
    state: present

# - name: Copy apache configuration for instance
#   template: 
#     src: templates/instance.conf
#     dest: /etc/httpd/conf.d/default.conf
#     notify: restart apache

- name: modify home page
  shell: 'echo "Hello World! This is Ansible demo @ AND" > /var/www/html/index.html'




