---
- name: install web server
  yum:
    name: httpd
    state: present

# - name: modify home page
#   shell: 'echo "Hello World! This is Ansible demo @ AND" > /var/www/html/index.html'

- name: copy html file to main path
  template:
    src: templates/index.html
    dest: /var/www/html/index.html
  notify: restart apache