---
- name: update OS on my Amazon Linux
  yum: 
    name: "*"
    state: latest
    update_cache: yes
    update_only: yes
  register: yum_update_status

- name: Add extras repository
  shell: yum-config-manager --enable extras
    
- name: install my applications
  yum:
    name: 
    - yum-utils 
    - device-mapper-persistent-data 
    - lvm2
    - curl 
    - wget 
    - unzip
    - aws-cfn-bootstrap 
    - nfs-utils 
    - chrony 
    - conntrack 
    - jq 
    - ec2-instance-connect 
    - socat
    - git
    - unzip 
    - awscli
    - python
    - containerd
    state: latest
    update_cache: true

- name: Start installed service apps
  command: echo "This task will start the installed apps services"
  notify:
    - start_new_service
  
- name: Remove packates not needed anymore
  yum:
    autoremove: yes