---
- name: restart apache
  ansible.builtin.service:
    name: httpd.service
    state: restarted
    enabled: yes

- name: restart nginx
  service: 
    name: nginx 
    state: restarted 
    enabled: yes