---
plugin: aws_ec2
aws_profile: and 
region: 
  - eu-central-1
keyed_groups:
  - key: tags.Contact
    prefix: tags
    value: alex.mavrogiannis
# filters: 
#   tag:Contact: alex.mavrogiannis
hostnames:
   - dns-name
compose:
  ansible_host: public_dns_name