---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for instance
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes