---
- name: update the system
  yum:
    name: "*"
    state: latest

- name: Enable docker package from amazon-linux-extras
  command: amazon-linux-extras enable docker

- name: Install container dependency containerd
  yum:
    name:
    - yum-utils 
    - lvm2
    - containerd
    - python
    - docker
  notify: 
    - restart containerd

- name: Install Docker module for Python
  pip:
    executable: pip3
    name: docker

- name: start docker
  ansible.builtin.service: 
    name: docker.service
    state: started
    enabled: yes
  become: true

