---
- name: install web server
  yum:
    name: httpd
    state: latest

- name: start web server
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: started

# - name: Copy nginx configuration for instance
#   template: 
#     src: ../template/instance.conf
#     dest: /etc/nginx/conf.d/default.conf
#   notify: restart nginx

- name: modify home page
  shell: 'echo "Hello World!" > /var/www/html/index.html'


# - name: Add epel-release repo
#   yum:
#     name: epel-release
#     state: present

# - name: Install nginx
#   yum: 
#     name: nginx 
#     state: presente

# - name: Copy website files to NGINX
#   copy:
#     src: "{{ app_root }}"
#     dest: "{{ document_root }}"
#     mode: preserve


