# - name: Setup Webserver - Ansible Demo @ AND
#   hosts: tags_Apache # tag_Contact_alex_mavrogiannis
#   become: yes
#   gather_facts: yes
#   become_method: sudo

#   roles:
#     - apache

- name: Setup Container - Ansible Demo @ AND
  hosts: tags_Docker
  become: yes
  gather_facts: no
  become_method: sudo

  roles:
    - container

# - name: Install Apps - Ansible Demo @ AND
#   hosts: tags_Packages 
#   become: yes
#   gather_facts: yes
#   become_method: sudo

#   roles:
#     - applications