- name: Install Nginx
  hosts: tag_Contact_alex_mavrogiannis
  become: yes
  # gather_facts: no
  become_method: sudo

  roles:
    - nginx # This points to the roles, utilizing the scripts under the roles directory. 
    # - applications