---
- name: update the system
  yum:
    name: "*"
    state: latest

- name: Enable docker package from amazon-linux-extras
  command: amazon-linux-extras enable docker

- name: Install container dependency containerd
  yum:
    name:
    - yum-utils 
    - lvm2
    - containerd
    - python
    - docker
  notify: 
    - restart containerd

- name: start docker
  ansible.builtin.service: 
    name: docker.service
    state: started
    enabled: yes
  become: true

- name: Install Docker module for Python
  pip:
    executable: pip3
    name: docker
  notify: 
    - restart docker

- name: deploy nginx docker container
  community.docker.docker_container:
    image: nginx:stable
    name: nginx
    state: present
    auto_remove: true
    ports:
      - "8080:80"